### ISSUE TITLE
Why use these codes, especially since they are all pass codes？

### ISSUE THREAD

**Issue by HuangZR-stu** [nik-dim/pamal#1]
https://github.com/nik-dim/pamal/blob/497622ed01f853207c012f74ed50f53839e0933e/src/trainer/multi_forward_ensemble_trainer.py#L131

All functions in the callback.py and base_callback.py files have a 'pass' internally

**Comment by nik-dim** [comment]
Hello, most of these functions are indeed not doing anything. However, they can be useful if you want to add some monitoring callbacks, e.g., track the evolution of the model, metrics etc. We simply added callbacks for everything similar to PyTorch Lightning. Hope this helps.
